% Email Server Settings

%Email Setup
mail = 'matlabtesting02@gmail.com';    % Replace with your email address
password = 'password12341.';          % Replace with your email password
server = 'smtp.gmail.com';     % Replace with your SMTP server



mailLabel = uicontrol('Parent', tab1,...
                      'Style', 'text',... 
                      'String', 'Email Address', ...
                      'HorizontalAlignment', 'left',...
                      'Position', [20 320 100 20]) ;
mailControl = uicontrol('Parent', tab1,...
                        'Style', 'edit',...
                        'String', {'Boston','New York',},...
                        'Position', [100 325 100 20],...
                        'Callback', @setmap); 
       
maxLabel = uicontrol('Parent', tab1,...
                     'Style', 'text',... 
                     'String', 'Max ($)', ...
                     'HorizontalAlignment', 'left',...
                     'Position', [20 295 100 20]) ;
maxControl = uicontrol('Parent', tab1,...
                       'Style', 'edit',...
                       'Position', [100 300 100 20],...
                       'Callback', @setmap);     

categoryLabel = uicontrol('Parent', tab1,...
                          'Style', 'text',... 
                          'String', 'Category', ...
                          'HorizontalAlignment', 'left',...
                          'Position', [20 270 100 20]) ;
categoryControl = uicontrol('Parent', tab1,...
                            'Style', 'popup',...
                            'String', {'Boston','New York',},...
                            'Position', [100 275 100 20],...
                            'Callback', @setmap);     